name: John Qing
description: 想写一辈子代码可以么？
url: "http://johnqing.github.io"

# Author info
author_name: Liu Qing
author_image_path: https://1.gravatar.com/avatar/fdfcf1e17124a1b949b98ddff70550a8
author_bio: |
    飘在帝都.
    拿过画笔的前端攻城狮.
    More <a href=/about/>about me</a>.

# External services
github_url: "https://github.com/johnqing"
weibo_url: "http://weibo.com/jonery"
email: "csssnow@gmail.com"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
pygments: true

# Links
links:
  - name: HTML老虎
    link: http://www.liuhehu.com/
  - name: 王迎然的博客
    link: http://www.wangyingran.com/
  - name: xiaoxiehang
    link: http://f2es.net/
  - name: Leesec's Blog
    link: http://www.leesec.com