
title: Liu Qing
author: Liu Qing
email: csssnow@gmail.com
host: http://johnqing.github.io
permalink: pretty
pygments: true
markdown: kramdown

index_pages:
    tag:
        title_prefix:   'Keyword: '

projects:

- title: n.js
  url:   https://github.com/johnqing/n.js
  desc:  A javascript framework.
  tech:  js

links:
  - title: HTML老虎
    url: http://www.liuhehu.com/
  - title: 王迎然的博客
    url: http://www.wangyingran.com/
  - title: xiaoxiehang
    url: http://f2es.net/
  - title: Leesec's Blog
    url: http://www.leesec.com
